"""
acquisition_state.py

Describes the camera state at which an ROI is captured.

Replaces a simple position_id with a richer state that accounts for
pan, tilt, zoom, and focus — parameters that affect what the camera
sees. This makes the ROI-to-acquisition mapping future-proof.

If later the system allows:

    Camera 1
    Position 5
    Zoom Level A
    Focus Distance B
    Lens C

...the AcquisitionState captures all of it without changing the ROI
configuration schema.

For today's system with positions 0-199:

    AcquisitionState(camera_id="cam_1", pan=0, tilt=0, zoom=0, focus=0)

...position_id is simply a convenience label on top of these values.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AcquisitionState:
    """
    Immutable snapshot of the camera state for which an ROI is valid.

    An ROI is defined *for* a specific acquisition state. When the
    camera moves to a different pan/tilt/zoom/focus combination, a
    different set of ROIs (or the same ROIs with different geometry)
    may apply.

    Responsibilities
    ----------------
    - Capture the camera parameters that affect ROI validity.
    - Serve as a lookup key for ROI sets.
    - Remain immutable so it can be used as a dict key.

    Must never:
    - Contain HALCON handles or GUI references.
    - Store runtime statistics or state.
    - Reference ROIConfiguration or RuntimeROI.

    Notes
    -----
    - For simple position-based systems, set unused axes to 0.
    - equality/hash are auto-generated by frozen dataclass.
    """

    camera_id: str

    pan: float = 0.0

    tilt: float = 0.0

    zoom: float = 0.0

    focus: float = 0.0

    @property
    def position_id(self) -> str:
        """
        Convenience label derived from pan.

        In the current system pan holds the 0-199 position index.
        This property exists for backward compatibility while the
        full system transitions to using all four axes.

        Returns
        -------
        str
            The position identifier string.
        """
        return str(int(self.pan))
